namespace Meta.Net.Sync.Types
{
    /// <summary>
    /// Supported synchronization operations.
    /// </summary>
    public enum DataSyncOperationType
    {
        UseCatalog,
        DisableTrigger,
        DisableForeignKey,
        DisableCheckConstraint,
        DropCheckConstraint,
        DropDefaultConstraint,
        DropIndex,
        DropForeignKey,
        DropUniqueConstraint,
        DropPrimaryKey,
        DropView,
        DropTrigger,
        DropTableValuedFunction,
        DropStoredProcedure,
        DropScalarFunction,
        DropInlineTableValuedFunction,
        DropAggregateFunction,
        DropUserTableColumn,
        DropUserTable,
        DropUserDefinedDataType,
        DropSchema,
        DropCatalog,
        CreateCatalog,
        CreateSchema,
        CreateUserDefinedDataType,
        CreateUserTable,
        AlterUserTable,
        AddUserTableColumn,
        AlterUserTableColumn,
        CreateAggregateFunction,
        CreateInlineTableValuedFunction,
        CreateScalarFunction,
        CreateStoredProcedure,
        CreateTableValuedFunction,
        CreateTrigger,
        CreateView,
        AlterAggregateFunction,
        AlterInlineTableValuedFunction,
        AlterScalarFunction,
        AlterStoredProcedure,
        AlterTableValuedFunction,
        AlterTrigger,
        AlterView,
        CreatePrimaryKey,
        TruncateTable,
        InsertRow,
        CreateUniqueConstraint,
        CreateForeignKey,
        CreateIndex,
        CreateCheckConstraint,
        CreateDefaultConstraint,
        EnableCheckContraint,
        EnableForeignKey,
        EnableTrigger,
        
    }
}
